// Run from the project root: node tests/engine.test.cjs
// No packages are required. Browser-only APIs are stubbed for this pure simulation suite.
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict');
const root=path.join(__dirname,'..');const ctx={window:{matchMedia:()=>({matches:false})},document:{getElementById:()=>null},console};vm.createContext(ctx);
vm.runInContext(fs.readFileSync(path.join(root,'src/model.js'),'utf8')+'\n'+fs.readFileSync(path.join(root,'src/engine.js'),'utf8')+'\nthis.api={newState,PinballWorld,engineConfig,calculateRate,TYPES,SKILLS,goal,reward,priceNew,priceLevel,spentSkills,skillRequirement,slotCount,normalizeSlots,validateState,rateSignature};',ctx);
const A=ctx.api;let count=0;
function test(name,fn){fn();count++;console.log('PASS',name);}
function approx(a,b,eps=1e-7){assert.ok(Math.abs(a-b)<eps,`${a} != ${b}`);}
function config(type='bar',skills={}){const s=A.newState();s.completed=20;s.stage=21;s.activeSkills=skills;s.inventory=[{id:1,type,level:1,slot:0,angle:type==='gate'?90:0,slot2:type==='portal'?1:undefined}];return A.engineConfig(s);}
function world(type='bar',skills={}){return new A.PinballWorld(config(type,skills),{seed:42,simulation:true});}
function ball(w){return w.newBall(200,300,0,100);}
function hits(w,n,b=ball(w)){for(let i=0;i<n;i++){w.time+=.2;w.hit(w.mods[0],b);}return b;}
function run(w,seconds){for(let i=0;i<Math.round(seconds*120);i++)w.step();}
test('document economy: first goals, rewards, complete tree cost',()=>{assert.equal(A.goal(1),800);assert.equal(A.goal(10),105500);assert.equal(A.reward(5),8);assert.equal(A.reward(10),9);assert.equal(A.reward(30),13);assert.equal(Object.values(A.SKILLS).reduce((n,x)=>n+x.costs.reduce((a,b)=>a+b,0),0),564);});
test('free starter bars do not increase paid-copy prices',()=>{const s=A.newState();assert.equal(A.priceNew(s,'bar'),20);assert.equal(A.priceLevel(s,s.inventory[0]),10);s.inventory.push({id:5,type:'bar',level:1,slot:4});assert.equal(A.priceNew(s,'bar'),36);s.inventory[4].slot=-1;assert.equal(A.priceNew(s,'bar'),36);});
test('skill prerequisites and socket cap',()=>{const s=A.newState();s.completed=20;s.phase='prep';assert.ok(A.skillRequirement(s,'B2'));s.skills.B1=2;assert.equal(A.skillRequirement(s,'B2'),'');s.skills.B4=2;s.skills.B5=2;assert.equal(A.skillRequirement(s,'B6'),'');assert.ok(A.skillRequirement(s,'B7'));s.skills.B6=1;assert.equal(A.skillRequirement(s,'B7'),'');assert.equal(A.slotCount(s),14);});
test('short launch exits the shooter lane',()=>{const w=world();w.launch(0,true);run(w,1);assert.ok(w.balls.length);assert.equal(w.balls[0].inLane,false);});
test('tap cooldown and no input income',()=>{const w=world();w.launch(.5,true);assert.equal(w.pulse(true),true);assert.equal(w.pulse(true),false);w.time+=.249;assert.equal(w.pulse(true),false);w.time+=.002;assert.equal(w.pulse(true),true);assert.equal(w.coinsEarned,0);});
test('contact cooldown per ball and globally per module',()=>{const w=world(),b=ball(w),b2=ball(w);assert.equal(w.hit(w.mods[0],b),true);assert.equal(w.hit(w.mods[0],b),false);w.time+=.04;assert.equal(w.hit(w.mods[0],b2),false);w.time+=.05;assert.equal(w.hit(w.mods[0],b2),true);w.time+=.08;assert.equal(w.hit(w.mods[0],b),true);approx(w.coinsEarned,3);});
test('series grows only across different modules',()=>{const s=A.newState(),w=new A.PinballWorld(A.engineConfig(s),{simulation:true}),b=ball(w);w.hit(w.mods[0],b);w.time+=.2;w.hit(w.mods[1],b);approx(w.combo,1.05);w.time+=.2;w.hit(w.mods[1],b);approx(w.combo,1.05);w.time+=2.1;w.step();approx(w.combo,1);});
test('level and additive coin bonuses',()=>{const w=world('bar',{B1:5,C1:5});w.mods[0].level=2;hits(w,1);approx(w.coinsEarned,1.35*1.7);approx(w.pointsEarned,10*1.35*1.3);});
test('perfect charges expire after three eligible hits',()=>{const w=world(),b=ball(w);b.perfect=3;b.perfectUntil=4;hits(w,4,b);approx(w.pointsEarned,47.5);assert.equal(b.perfect,0);});
test('bar L5 doubles every fifth physical hit',()=>{const w=world();w.mods[0].level=5;hits(w,5);approx(w.pointsEarned,60*Math.pow(1.35,4));});
test('spinner pays every fourth contact without recursive events',()=>{const w=world('spinner');hits(w,4);approx(w.coinsEarned,7);approx(w.pointsEarned,72);assert.equal(w.runHits,4);});
test('bank pays after five physical hits',()=>{const w=world('bank');hits(w,5);approx(w.coinsEarned,17);approx(w.pointsEarned,125);assert.equal(w.runHits,5);});
test('stationary friction produces no rewards',()=>{const w=world(),m=w.mods[0];w.balls=[w.newBall(m.x,m.y-12.2,0,0)];run(w,2);assert.equal(w.runHits,0);});
test('gate direction and non-stacking charges',()=>{const w=world('gate'),m=w.mods[0];w.balls=[w.newBall(m.x,m.y-1,0,300)];run(w,.02);assert.equal(w.runHits,1);assert.equal(w.balls[0].gate,3);const r=world('gate'),mr=r.mods[0];r.balls=[r.newBall(mr.x,mr.y+1,0,-300)];run(r,.02);assert.equal(r.runHits,0);});
test('portal transfers to output, not a second paid collision',()=>{const w=world('portal'),m=w.mods[0],out=w.slots[m.slot2];w.balls=[w.newBall(m.x,m.y,300,0)];w.step();assert.equal(w.runHits,1);assert.ok(Math.hypot(w.balls[0].x-out.x,w.balls[0].y-out.y)<35);assert.ok(w.balls[0].cool.portal>w.time);});
test('magnet holds and releases without repeated reward',()=>{const w=world('magnet'),m=w.mods[0];m.a=-Math.PI/2;w.balls=[w.newBall(m.x,m.y,0,200)];w.step();assert.ok(w.balls[0].held);run(w,.2);assert.equal(w.balls[0].held,null);assert.ok(w.balls[0].vy<0);assert.equal(w.runHits,1);});
test('multiball has a hard limit of three and timed copies',()=>{const cfg=config();cfg.inventory.push({id:2,type:'multi',level:1,slot:1,angle:0});const w=new A.PinballWorld(cfg,{simulation:true});const b=ball(w);w.balls=[b];hits(w,20,b);assert.equal(w.balls.length,3);assert.equal(w.balls.filter(b=>Number.isFinite(b.ttl)).length,2);hits(w,20,b);assert.equal(w.balls.length,3);assert.ok(w.mods[1].nextAction>w.time);});
test('coin piggy bank is separate from qualified field income',()=>{let gifts=0;const w=new A.PinballWorld(config('bar',{C5:3}),{simulation:true,onEvent:e=>{if(e.type==='reward'&&!e.qualified)gifts+=e.coins;}});hits(w,50);approx(gifts,15);approx(w.coinsEarned,65);});
test('manual insurance saves exactly once',()=>{const w=world('bar',{A6:1});w.launch(.6,true);w.lastPerfect=w.time;Object.assign(w.balls[0],{x:200,y:730,inLane:false});w.step();assert.equal(w.balls.length,1);assert.equal(w.insured,true);Object.assign(w.balls[0],{x:200,y:730,inLane:false});w.step();assert.equal(w.balls.length,0);});
test('manual intervention disables automatic insurance',()=>{const w=world('bar',{D7:1});w.launch(.6,false);w.pulse(true);Object.assign(w.balls[0],{x:200,y:730,inLane:false});w.step();assert.equal(w.balls.length,0);});
test('maximum speed is clamped after collision resolution',()=>{const w=world();w.balls=[w.newBall(200,170,2500,-2000)];w.step();assert.ok(Math.hypot(w.balls[0].vx,w.balls[0].vy)<=1100.0001);});
test('offline median is deterministic and never mutates the profile',()=>{const s=A.newState();s.completed=3;s.stage=4;const before=JSON.stringify(s),a=A.calculateRate(s),b=A.calculateRate(s);approx(a,b);assert.ok(a>0);assert.equal(JSON.stringify(s),before);});
test('save validation preserves resources and planner without replaying rewards',()=>{const s=A.newState();s.stage=21;s.completed=20;s.coins=123.45;s.gems=9;s.activeSkills={D6:1};s.planner={enabled:true,reserve:30,ratio:.25,mode:'order',cursor:2};const v=A.validateState(JSON.parse(JSON.stringify(s)));assert.equal(v.coins,s.coins);assert.equal(v.gems,9);assert.equal(v.stage,21);assert.equal(v.planner.enabled,true);assert.equal(v.planner.reserve,30);});

test('fresh profile has assisted flippers but manual spring',()=>{const s=A.newState(),w=new A.PinballWorld(A.engineConfig(s),{simulation:true});assert.equal(s.autoFlippers,true);assert.equal(s.auto,false);assert.equal(w.autoFlippers,true);run(w,7);assert.equal(w.balls.length,0);});
test('auto-flippers work on field one with no skill unlock',()=>{const s=A.newState(),w=new A.PinballWorld(A.engineConfig(s),{simulation:true});w.rng=()=>0;w.balls=[w.newBall(175,606,0,180)];run(w,.12);assert.ok(w.flipAt>=0);assert.equal(w.flipManual,false);assert.equal(w.runPerfect,0);});
test('disabled auto-flippers never issue a pulse',()=>{const s=A.newState();s.autoFlippers=false;const w=new A.PinballWorld(A.engineConfig(s),{simulation:true});w.rng=()=>0;w.balls=[w.newBall(175,606,0,180)];run(w,.12);assert.equal(w.flipAt,-100);});
test('legacy save enables assist while an explicit opt-out is preserved',()=>{const s=A.newState();delete s.autoFlippers;assert.equal(A.validateState(s).autoFlippers,true);s.autoFlippers=false;assert.equal(A.validateState(s).autoFlippers,false);});
test('manual spring and automatic spring are independently configured',()=>{const s=A.newState();s.stage=4;s.completed=3;s.autoFlippers=false;s.auto=true;const w=new A.PinballWorld(A.engineConfig(s),{simulation:true});run(w,3);assert.equal(w.autoFlippers,false);assert.ok(w.balls.length>0);});

console.log(`\n${count} / ${count} engine tests passed.`);
